sudo: false

language:
  - python

python:
  - 2.7
  - 3.6

install:
  - /opt/anaconda3/bin/pip install pytest

script:
  - /opt/anaconda3/bin/pytest --verbose example.py

notifications:
  email: false

